# Generated by Django 3.0.7 on 2020-07-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('review', models.CharField(max_length=400)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Page')),
            ],
        ),
    ]
