# Generated by Django 3.0.7 on 2020-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='rating',
            name='favorite',
            field=models.SmallIntegerField(default=1),
        ),
    ]
