# Generated by Django 3.0.7 on 2020-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200707_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='favorite',
            field=models.SmallIntegerField(),
        ),
    ]
