# Generated by Django 3.0.7 on 2020-07-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200707_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(max_length=128),
        ),
    ]
