# Generated by Django 3.0.7 on 2020-07-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20200707_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
